version: '3.8'

services:

  init-static:
    image: ghcr.io/imirjar/plyglo-website:latest
    volumes:
      - plyglo-website:/app/dist

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - plyglo-website:/usr/share/caddy:ro 
    depends_on:
      init-static:
        condition: service_completed_successfully

volumes:
  plyglo-website: